CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=30
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=30
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=30
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Touchpad / I2C
CONFIG_I2C=y
CONFIG_ZMK_POINTING=y

# Improve Bluetooth connection stability and pointer latency
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Set Bluetooth Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="MonoTypist"