include:
  # 1. Standard (Macros enabled by default because SIMPLE_MODE=0)
  # - board: monogreen
  #   shield: v4_2_left
  #   artifact-name: v4_2_macro_left_firmware

  - board: monogreen
    shield: v4_2_da_left
    artifact-name: v4_2_da_macro_left_firmware

  # 2. Simple Mode (Numbers instead of Macros)
  # - board: monogreen
  #   shield: v4_2_left
  #   cmake-args: -DEXTRA_CFLAGS="-DSIMPLE_MODE=1"
  #   artifact-name: v4_2_simple_left_firmware

  - board: monogreen
    shield: v4_2_da_left
    cmake-args: -DEXTRA_CFLAGS="-DSIMPLE_MODE=1"
    artifact-name: v4_2_da_simple_left_firmware
