include:
  # 1. Standard (Macros enabled by default)
  - board: monogreen
    shield: v4_2_hu_left
    artifact-name: v4_2_hu_macro_left_firmware

  - board: monogreen
    shield: v4_2_da_left
    artifact-name: v4_2_da_macro_left_firmware

  # 2. Simple Mode (Numbers instead of Macros)
  - board: monogreen
    shield: v4_2_hu_simple_left
    artifact-name: v4_2_hu_simple_left_firmware

  - board: monogreen
    shield: v4_2_da_simple_left
    artifact-name: v4_2_da_simple_left_firmware
