manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/torjek
    - name: grassfedreeve
      url-base: https://github.com/grassfedreeve
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-katori
      remote: grassfedreeve
      revision: main
  self:
    path: config
